# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf14' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf14
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Auth'

  target 'rnf14Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf14-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf14-tvOS

  target 'rnf14-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
