# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf8
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # target 'rnf8-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf8-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf8-tvOS

  target 'rnf8-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
