# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf20' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf20
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # target 'rnf20-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf20Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf20-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf20-tvOS

  target 'rnf20-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
