# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf16' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf16
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Auth'

  # target 'rnf16-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf16Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf16-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf16-tvOS

  target 'rnf16-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
