# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf12' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf12
	pod 'Firebase/Core'
	pod 'Firebase/Auth'

  # target 'rnf12-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf12Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf12-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf12-tvOS

  target 'rnf12-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
