# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf21' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf21
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # target 'rnf21-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf21Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf21-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf21-tvOS

  target 'rnf21-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
