# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnf4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf4
  pod 'Firebase/Core'

  target 'rnf4-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rnf4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
