# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf19' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf19
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # target 'rnf19-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf19-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf19-tvOS

  target 'rnf19-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
