# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf9' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf9
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # target 'rnf9-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf9-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf9-tvOS

  target 'rnf9-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
