# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf5' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf5
  pod 'Firebase/Core'

  target 'rnf5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf5-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf5-tvOS

  target 'rnf5-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
