# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnf22' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf22
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # target 'rnf22-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'rnf22Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnf22-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnf22-tvOS

  target 'rnf22-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
